# Generated by Django 4.1 on 2025-01-12 23:05

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=7)),
                ('estado', models.IntegerField(default=0)),
                ('nroinforme', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idasistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('idcampo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.IntegerField(blank=True, null=True)),
                ('id_areaejemplo', models.CharField(blank=True, max_length=50, null=True)),
                ('id_area', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idcargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='0', max_length=500, null=True)),
                ('estado', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cite',
            fields=[
                ('idcite', models.AutoField(primary_key=True, serialize=False)),
                ('id_area', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idcontrato', models.AutoField(primary_key=True, serialize=False)),
                ('id_contratante', models.IntegerField(blank=True, null=True)),
                ('id_empleado', models.IntegerField(blank=True, null=True)),
                ('lugartrabajo', models.CharField(blank=True, max_length=15, null=True)),
                ('fechaingreso', models.DateField(blank=True, null=True)),
                ('fechasalida', models.DateField(blank=True, null=True)),
                ('cuentabanco', models.CharField(blank=True, max_length=32, null=True)),
                ('nombrebanco', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleInforme',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_informe', models.IntegerField(blank=True, default=0, null=True)),
                ('antecedentes', models.CharField(blank=True, default='0', max_length=1000, null=True)),
                ('analisis', models.CharField(blank=True, default='0', max_length=1000, null=True)),
                ('desarrollo', models.CharField(blank=True, default='0', max_length=1000, null=True)),
                ('conclusion', models.CharField(blank=True, default='0', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProveido',
            fields=[
                ('idestado_proveido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoRuta',
            fields=[
                ('idestado_ruta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperienciaLaboral', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=100)),
                ('cargoEmpresa', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.IntegerField(default=0)),
                ('id_usuario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('idflujo', models.AutoField(primary_key=True, serialize=False)),
                ('id_campo', models.IntegerField(blank=True, null=True)),
                ('id_area', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('id_proceso', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Formacion',
            fields=[
                ('idformacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('institucion', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(default=0)),
                ('id_usuario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('idinforme', models.AutoField(primary_key=True, serialize=False)),
                ('cite', models.CharField(max_length=15)),
                ('fechacreacion', models.DateTimeField()),
                ('id_autor', models.IntegerField(blank=True, null=True)),
                ('id_destinatario', models.IntegerField(blank=True, null=True)),
                ('referencia', models.CharField(max_length=500)),
                ('resumen', models.CharField(max_length=10000)),
                ('adjuntoexterno', models.CharField(blank=True, max_length=200, null=True)),
                ('fechaaceptado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=15, null=True)),
                ('id_ruta', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('idproceso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProcesoProveido',
            fields=[
                ('idproceso_proveido', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.IntegerField()),
                ('id_categoria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('nit', models.CharField(blank=True, max_length=25, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('observacion', models.CharField(blank=True, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveido',
            fields=[
                ('idproveido', models.AutoField(primary_key=True, serialize=False)),
                ('id_emisor', models.IntegerField()),
                ('id_receptor', models.IntegerField(blank=True, null=True)),
                ('fecha_plazo_n', models.DateField(blank=True, null=True)),
                ('fecha_remitido', models.DateTimeField()),
                ('fecha_aceptado', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesando', models.DateTimeField(blank=True, null=True)),
                ('fecha_concluido', models.DateTimeField(blank=True, null=True)),
                ('asunto', models.CharField(blank=True, max_length=500, null=True)),
                ('cite', models.CharField(blank=True, max_length=20, null=True)),
                ('adjunto_externo', models.CharField(blank=True, max_length=200, null=True)),
                ('id_tipo_documento', models.IntegerField(blank=True, null=True)),
                ('id_estado_proveido', models.IntegerField(blank=True, null=True)),
                ('id_proceso_proveido', models.IntegerField(blank=True, null=True)),
                ('id_ruta', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelacionFamiliar',
            fields=[
                ('idrelacionFamiliar', models.AutoField(primary_key=True, serialize=False)),
                ('tipoRelacion', models.CharField(blank=True, max_length=30, null=True)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('codigoSeguro', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.IntegerField(default=0)),
                ('id_usuario', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('idruta', models.AutoField(primary_key=True, serialize=False)),
                ('id_autor', models.IntegerField()),
                ('fecha_iniciada', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesada', models.DateTimeField(blank=True, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('id_estado_ruta', models.IntegerField(blank=True, default=1, null=True)),
                ('id_estado_proveido', models.IntegerField(blank=True, default=1, null=True)),
                ('id_area', models.IntegerField(blank=True, null=True)),
                ('id_ruta_tipo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutaTipo',
            fields=[
                ('idruta_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCabecera',
            fields=[
                ('idsolicitud_cabecera', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=11)),
                ('trabajo', models.IntegerField(default=0)),
                ('estado', models.CharField(default='0', max_length=15)),
                ('id_proveedor', models.IntegerField(default=0)),
                ('id_usuario', models.IntegerField(default=0)),
                ('id_proceso', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('idsolicitud_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_producto', models.IntegerField()),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('preciounitario', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('detalle', models.CharField(blank=True, max_length=1000, null=True)),
                ('id_solicitud_cabecera', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudObservacion',
            fields=[
                ('idsolicitud_observacion', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.IntegerField()),
                ('id_solicitud_detalle', models.IntegerField()),
                ('id_campo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idtipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('codigoUsuario', models.CharField(blank=True, max_length=16, null=True)),
                ('apellidoPaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(blank=True, max_length=50, null=True)),
                ('grado', models.CharField(blank=True, max_length=200, null=True)),
                ('fuerza', models.CharField(blank=True, max_length=200, null=True)),
                ('regimiento', models.CharField(blank=True, max_length=200, null=True)),
                ('carnetMilitar', models.CharField(blank=True, max_length=50, null=True)),
                ('fotoPerfil', models.CharField(blank=True, max_length=100, null=True)),
                ('ci', models.IntegerField(blank=True, null=True)),
                ('expedido', models.CharField(blank=True, max_length=15, null=True)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('estadoCivil', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=50, null=True)),
                ('tipoLicencia', models.CharField(blank=True, max_length=50, null=True)),
                ('codigoSeguro', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('codigoBiometrico', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.IntegerField(default=1)),
                ('rol', models.CharField(blank=True, max_length=20, null=True)),
                ('id_cargo', models.IntegerField(blank=True, null=True)),
                ('id_dependencia_cargo', models.IntegerField(blank=True, null=True)),
                ('id_area', models.IntegerField(blank=True, null=True)),
                ('cfgConductoRegular', models.IntegerField(blank=True, null=True)),
                ('cfgNuevoInforme', models.IntegerField(blank=True, null=True)),
                ('cfgAccesoRutas', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
