# Generated by Django 4.1 on 2025-01-12 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='valor_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='valor_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='fecha_modificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informe',
            name='valor_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='valor_anterior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('admin', 'Admin'), ('superadmin', 'SuperAdmin')], max_length=20, null=True),
        ),
    ]
