# Generated by Django 4.1 on 2025-01-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_asistencia_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
    ]
