# Generated by Django 4.1 on 2025-01-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_area_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table=None,
        ),
    ]
